#
# Android/PojavLauncher/ZalithLauncher specific Gradle properties
# Use: gradle build -Pbuild.target=android
#
kotlin.code.style=official
kotlin.incremental=true
kotlin.caching.enabled=true
kotlin.parallel.tasks.in.project=true

# Low memory for Termux
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xms256m -Xmx1536m -XX:+UseG1GC

mod_version=0.39.0
mod_mc_version=>26.1.2 <26.3
maven_group=net.ccbluex
archives_base_name=liquidbounce

build.target=android
